### ISSUE TITLE
cant make it work

### ISSUE THREAD

**Issue by pablopeu** [sefose/webcam_to_prusa_connect#1]
Hi non experienced user here, followed your github procedure but the camera does not show up in prusa connect, tried these combinations /dev/video0 and v4l2:/dev/video0

it shows like this: HD Web Camera: HD Web Camera (usb-3f980000.usb-1.1.3): /dev/video0

rebooted after every change, no luck yet

do I need to start something previous to reboot?

btw, camera works perfect via octoprint, can be this be a conflict or the same stream can be used for both?

Thanks

CAMERA_NAMES=("Prusacam")

CAMERA_DEVICES=("v4l2:/dev/video0")

CAMERA_RESOLUTIONS=("1920x1080")

CAMERA_OPTIONS=("--jpeg 95 -S 20")

TOKENS=("mytoken")

**Comment by sefose** [comment]
Hello - sorry for the inconvenience,
could you run the webcam_to_prusa_connect.sh in the terminal and post some logs?

**Comment by pablopeu** [comment]
it seems its indeed a problem if octoprint is using the camera feed right?
```
 ./webcam_to_prusa_connect.sh
Input variables:
Camera 1, Name: Prusacam, XXXXXXXX
Processing camera: 1
Name: Prusacam
Token: XXXXXXXXXXX
Fingerprint: camera0000000001
------
--- Opening v4l2:/dev/video0...
/dev/video0 opened.
No input was specified, using the first.
Error selecting input 0
VIDIOC_S_INPUT: Device or resource busy
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

#######

```

**Comment by sefose** [comment]
I think your first idea was right: this device seems blocked by octoprint.
To fully prove this, you maybe could remove the cam from octoprint and test it again.

Octoprint seems to provide a rtsp stream. The purpose of this script was to not use such a stream, because prusa connect uses single pictures only.

I think the upload.sh from here should work.
[https://www.reddit.com/r/prusa3d/comments/1971673/streaming_a_webcam_via_rtsp_to_prusa_connect/](https://www.reddit.com/r/prusa3d/comments/1971673/streaming_a_webcam_via_rtsp_to_prusa_connect/)

This was the starting point for my script and I removed the need for a rtsp stream.

**Comment by pablopeu** [comment]
Thanks!! Maybe the solution is easier, I just remembered that the Octoprint install of the camera streamer allows to take snapshots, you just need to change a parameter in the address:

http://192.168.1.100/webcam/?action=snapshot

this provides a static image that could be feed to Prusa connect, but I don't know how to implement this, maybe you can help, the solution will also help all current octoprint users.

If you don't have the time, any pointer on how to do it will help, I "programmed" some solutions with the help of Claude and ChatGPT

Thanks again!

**Comment by pablopeu** [comment]
Thanks!! Maybe the solution is easier, I just remembered that the Octoprint install of the camera streamer allows to take snapshots, you just need to change a parameter in the address:

http://192.168.1.100/webcam/?action=snapshot

this provides a static image that could be feed to Prusa connect, but I don't know how to implement this, maybe you can help, the solution will also help all current octoprint users.

If you don't have the time, any pointer on how to do it will help, I "programmed" some solutions with the help of Claude and chatgpt

Thanks again!

**Comment by pablopeu** [comment]
Never mind, kept looking and found an octoprint plugin that does exactly this. It requests the camera token and then does the api call and everything else: https://github.com/rizz360/prusa_connect_uploader

Thanks for the help, I'm closing this issue.
